// Shared PDF builder for the export-report-pdf Edge Function. Pure
// function — takes the report + its transactions and returns the bytes
// of a PDF file. The function fetches no IO: the caller passes in the
// data it already loaded. Watermark PNG is also passed in (read from
// disk by the Edge Function) so this module has no filesystem deps.
//
// Why a separate shared lib (not inlined into the function): the build
// is non-trivial (~150 lines, lots of layout math) and unit-testable
// in isolation. Keeping it under _shared/lib mirrors the rest of the
// code base (document-analysis, transaction-agent, etc.).
//
// Layout — Letter (612 × 792 pt), 50pt margins. Each page paints:
//   1. The full-page watermark (logo PNG, low-alpha, centered)
//   2. The header band (logo + brand + generated-at)
//   3. The footer (page number + "Generated by Money Tracker")
// Content pages carry the rest of the report (title, summary,
// transactions table). Pagination is automatic: when a row doesn't
// fit, we add a fresh page and repeat the table header.
//
// Colors are mapped from the same CSS variables the frontend uses
// (see packages/frontend/src/index.css) so the PDF shares its visual
// language with the on-screen report.
import {
  PDFDocument,
  rgb,
  StandardFonts,
  type PDFFont,
} from "npm:pdf-lib@1.17.1";

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN_X = 50;
const MARGIN_Y = 50;

// Colors mapped from packages/frontend/src/index.css (gray-900, gray-500,
// f9fafb, d9dadb/text-secondary/20, emerald-700, rose-700, slate-900).
// pdf-lib's `rgb()` takes 0-1 floats; comments preserve the source hex.
const COLOR_TEXT_PRIMARY = rgb(0.067, 0.094, 0.153); // #111827
const COLOR_TEXT_SECONDARY = rgb(0.42, 0.45, 0.5); //  #6b7280
const COLOR_BORDER = rgb(0.85, 0.86, 0.87); //             text-secondary/20
const COLOR_BG_SECONDARY = rgb(0.976, 0.98, 0.984); //      #f9fafb
const COLOR_HEADER_RULE = rgb(0.82, 0.84, 0.86); //         slate-300
const COLOR_INCOME = rgb(0.027, 0.471, 0.341); //           emerald-700
const COLOR_EXPENSE = rgb(0.745, 0.071, 0.235); //          rose-700

export interface PdfLabel {
  brand: string;
  reportLabel: string;
  statusActive: string;
  statusArchived: string;
  summaryHeader: string;
  income: string;
  expenses: string;
  net: string;
  transactions: string;
  countSuffix: string;
  noTransactions: string;
  tableDate: string;
  tableMerchant: string;
  tableCategory: string;
  tableType: string;
  tableAmount: string;
  pageLabel: string;
  generatedBy: string;
  noDateRange: string;
}

export interface BuildReportPdfInput {
  report: {
    id: string;
    title: string;
    description: string | null;
    status: string;
    dateRangeStart: string | null;
    dateRangeEnd: string | null;
    createdAt: string;
    archivedAt: string | null;
  };
  transactions: Array<{
    id: string;
    name: string | null;
    merchant: string;
    amount: number;
    currency: string;
    transactionDate: string;
    category: string;
    transactionType: string;
  }>;
  perCurrency: Array<{
    currency: string;
    transactionCount: number;
    totalIncome: number;
    totalExpenses: number;
    net: number;
  }>;
  watermarkPng: Uint8Array | null;
  labels: PdfLabel;
  /** Localized "currency formatter" — e.g. "$1,234.56" or "ARS 1.234,56". */
  formatCurrency: (amount: number, currency: string) => string;
  /** ISO date or null. Locale-aware formatter — e.g. "2026-07-05" or "05/07/2026". */
  formatDate: (date: string | null) => string;
}

export async function buildReportPdf(
  input: BuildReportPdfInput
): Promise<Uint8Array> {
  const {
    report,
    transactions,
    perCurrency,
    watermarkPng,
    labels,
    formatCurrency,
    formatDate,
  } = input;

  const pdf = await PDFDocument.create();
  const helvetica = await pdf.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const watermark =
    watermarkPng && watermarkPng.length > 0
      ? await pdf.embedPng(watermarkPng)
      : null;

  // Page state — every helper increments `page` so the watermark can
  // be re-painted onto each new page.
  const ctx = {
    pdf,
    helvetica,
    helveticaBold,
    watermark,
    labels,
    formatCurrency,
    formatDate,
    page: pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    pageNumber: 1,
  };

  drawWatermark(ctx);
  drawHeaderBand(ctx);

  // Cursor starts below the header band. Layout moves the cursor
  // upward (`drawY -= height`) so the table can spill onto new pages.
  let cursorY = PAGE_HEIGHT - MARGIN_Y - 90;

  cursorY = drawTitleBlock(ctx, report, cursorY);
  cursorY = drawSummary(ctx, perCurrency, cursorY);

  cursorY = drawTransactionsTable(ctx, transactions, cursorY);

  drawFooter(ctx, cursorY);
  return await pdf.save();
}

// ─── layout primitives ──────────────────────────────────────────────────────

function drawWatermark(ctx: PdfContext): void {
  if (!ctx.watermark) return;
  // Draw the logo centered on the page, sized to ~70% of page width.
  // The PNG already has alpha baked (~12%); pdf-lib draws PNGs with
  // their alpha channel preserved, so the watermark composites
  // properly over everything else.
  const watermarkWidth = PAGE_WIDTH * 0.7;
  const aspect = ctx.watermark.width / ctx.watermark.height;
  const w = watermarkWidth;
  const h = w / aspect;
  const x = (PAGE_WIDTH - w) / 2;
  const y = (PAGE_HEIGHT - h) / 2;
  ctx.page.drawImage(ctx.watermark, { x, y, width: w, height: h });
}

function drawHeaderBand(ctx: PdfContext): void {
  const { page } = ctx;
  // Footer ruled line and header divider. Same slate-300 hue the
  // frontend uses for top-of-card borders (the `border` CSS variable).
  const y = PAGE_HEIGHT - MARGIN_Y;
  page.drawLine({
    start: { x: MARGIN_X, y },
    end: { x: PAGE_WIDTH - MARGIN_X, y },
    thickness: 1,
    color: COLOR_BORDER,
  });

  // "Money Tracker" brand — left side, bold
  page.drawText("Money Tracker", {
    x: MARGIN_X,
    y: y + 18,
    size: 14,
    font: ctx.helveticaBold,
    color: COLOR_TEXT_PRIMARY,
  });

  // "Report · 2026-07-05" right-aligned
  const dateStr = formatDateLocalized(new Date().toISOString(), ctx);
  const right = `${ctx.labels.reportLabel} · ${dateStr}`;
  const rightWidth = ctx.helvetica.widthOfTextAtSize(right, 10);
  page.drawText(right, {
    x: PAGE_WIDTH - MARGIN_X - rightWidth,
    y: y + 22,
    size: 10,
    font: ctx.helvetica,
    color: COLOR_TEXT_SECONDARY,
  });
}

function drawTitleBlock(
  ctx: PdfContext,
  report: BuildReportPdfInput["report"],
  cursorY: number
): number {
  const { page, helveticaBold, helvetica } = ctx;

  // Title — 22pt bold
  page.drawText(report.title, {
    x: MARGIN_X,
    y: cursorY - 22,
    size: 22,
    font: helveticaBold,
    color: COLOR_TEXT_PRIMARY,
  });
  let y = cursorY - 22;

  // Status pill — small rounded bg with label inside (drawn as two
  // lines + bg rectangle since pdf-lib has no rounded-rect primitive).
  const status = report.status === "archived" ? "archived" : "active";
  if (status === "active") {
    // Active uses emerald styling.
    drawPill(
      page,
      helvetica,
      ctx.labels.statusActive,
      MARGIN_X,
      y - 4,
      "active"
    );
  } else {
    drawPill(
      page,
      helvetica,
      ctx.labels.statusArchived,
      MARGIN_X,
      y - 4,
      "archived"
    );
  }
  y -= 26;

  // Description (optional)
  if (report.description) {
    const lines = wrapText(
      helvetica,
      report.description,
      PAGE_WIDTH - 2 * MARGIN_X - 80,
      11
    );
    for (const line of lines) {
      page.drawText(line, {
        x: MARGIN_X,
        y: y - 11,
        size: 11,
        font: helvetica,
        color: COLOR_TEXT_SECONDARY,
      });
      y -= 14;
    }
  }

  // Date range
  const range = formatDateRange(report, ctx);
  if (range) {
    page.drawText(range, {
      x: MARGIN_X,
      y: y - 11,
      size: 10,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    y -= 16;
  }

  return y - 8; // small breathing room before the next section
}

function drawSummary(
  ctx: PdfContext,
  perCurrency: BuildReportPdfInput["perCurrency"],
  cursorY: number
): number {
  const { page, helveticaBold, helvetica, formatCurrency, labels } = ctx;

  if (perCurrency.length === 0) {
    page.drawText(labels.noTransactions, {
      x: MARGIN_X,
      y: cursorY - 14,
      size: 11,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    return cursorY - 26;
  }

  // Section header
  page.drawText(labels.summaryHeader, {
    x: MARGIN_X,
    y: cursorY - 12,
    size: 9,
    font: helvetica,
    color: COLOR_TEXT_SECONDARY,
  });
  let y = cursorY - 18;

  // One card per currency, stacked vertically (multi-currency reports
  // are rare — most users have one primary currency).
  for (const bucket of perCurrency) {
    const blockHeight = 56;
    if (y - blockHeight < MARGIN_Y + 60) {
      ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      ctx.pageNumber += 1;
      drawWatermark(ctx);
      drawHeaderBand(ctx);
      y = PAGE_HEIGHT - MARGIN_Y - 90;
    }

    // Card
    const cardX = MARGIN_X;
    const cardY = y - blockHeight;
    const cardW = PAGE_WIDTH - 2 * MARGIN_X;
    page.drawRectangle({
      x: cardX,
      y: cardY,
      width: cardW,
      height: blockHeight,
      borderColor: COLOR_BORDER,
      borderWidth: 1,
      color: rgb(1, 1, 1),
    });

    // Currency label (top-left)
    page.drawText(bucket.currency, {
      x: cardX + 12,
      y: cardY + blockHeight - 16,
      size: 10,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
    // Count (top-right)
    const countText = `${bucket.transactionCount} ${labels.countSuffix}`;
    const countWidth = helvetica.widthOfTextAtSize(countText, 9);
    page.drawText(countText, {
      x: cardX + cardW - 12 - countWidth,
      y: cardY + blockHeight - 16,
      size: 9,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });

    // Income row
    page.drawText(labels.income, {
      x: cardX + 12,
      y: cardY + blockHeight - 32,
      size: 11,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    const income = formatCurrency(bucket.totalIncome, bucket.currency);
    const incomeW = helveticaBold.widthOfTextAtSize(income, 11);
    page.drawText(income, {
      x: cardX + cardW - 12 - incomeW,
      y: cardY + blockHeight - 32,
      size: 11,
      font: helveticaBold,
      color: COLOR_INCOME,
    });

    // Expenses row
    page.drawText(labels.expenses, {
      x: cardX + 12,
      y: cardY + blockHeight - 46,
      size: 11,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    const expenses = formatCurrency(bucket.totalExpenses, bucket.currency);
    const expensesW = helveticaBold.widthOfTextAtSize(expenses, 11);
    page.drawText(expenses, {
      x: cardX + cardW - 12 - expensesW,
      y: cardY + blockHeight - 46,
      size: 11,
      font: helveticaBold,
      color: COLOR_EXPENSE,
    });

    y -= blockHeight + 8;
  }

  return y;
}

function drawTransactionsTable(
  ctx: PdfContext,
  transactions: BuildReportPdfInput["transactions"],
  cursorY: number
): number {
  const { page, helveticaBold, helvetica, formatCurrency, labels } = ctx;

  if (transactions.length === 0) {
    return cursorY;
  }

  let y = startNewPageIfNeeded(ctx, cursorY, 40);

  // Section header
  page.drawText(`${labels.transactions} (${transactions.length})`, {
    x: MARGIN_X,
    y: y - 12,
    size: 9,
    font: helveticaBold,
    color: COLOR_TEXT_SECONDARY,
  });
  y -= 18;

  // Column layout (x positions and widths)
  const cols = {
    date: { x: MARGIN_X + 4, width: 64 },
    merchant: { x: MARGIN_X + 76, width: 150 },
    category: { x: MARGIN_X + 234, width: 110 },
    type: { x: MARGIN_X + 352, width: 50 },
    amount: {
      x: PAGE_WIDTH - MARGIN_X - 70,
      width: 66,
      rightAligned: true,
    } as { x: number; width: number; rightAligned: true },
  };

  const drawTableHeader = () => {
    const headerY = y - 12;
    // Background row
    page.drawRectangle({
      x: MARGIN_X,
      y: headerY - 8,
      width: PAGE_WIDTH - 2 * MARGIN_X,
      height: 20,
      color: COLOR_BG_SECONDARY,
    });
    page.drawText(labels.tableDate, {
      x: cols.date.x,
      y: headerY,
      size: 8,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
    page.drawText(labels.tableMerchant, {
      x: cols.merchant.x,
      y: headerY,
      size: 8,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
    page.drawText(labels.tableCategory, {
      x: cols.category.x,
      y: headerY,
      size: 8,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
    page.drawText(labels.tableType, {
      x: cols.type.x,
      y: headerY,
      size: 8,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
    page.drawText(labels.tableAmount, {
      x: cols.amount.x,
      y: headerY,
      size: 8,
      font: helveticaBold,
      color: COLOR_TEXT_SECONDARY,
    });
  };

  drawTableHeader();
  y -= 22;

  for (const tx of transactions) {
    // Each row is 18pt tall. Reserve 60pt for footer when starting a
    // new page for the last row.
    if (y - 18 < MARGIN_Y + 50) {
      ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      ctx.pageNumber += 1;
      drawWatermark(ctx);
      drawHeaderBand(ctx);
      y = PAGE_HEIGHT - MARGIN_Y - 50;
      drawTableHeader();
      y -= 22;
    }

    const isIncome =
      tx.transactionType === "income" || tx.transactionType === "ingreso";
    const sign = isIncome ? "↑" : "↓";

    const date = ctx.formatDate(tx.transactionDate);
    page.drawText(date, {
      x: cols.date.x,
      y: y - 8,
      size: 9,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    const merchant = tx.name && tx.name.length > 0 ? tx.name : tx.merchant;
    page.drawText(truncate(helvetica, merchant, cols.merchant.width, 9), {
      x: cols.merchant.x,
      y: y - 8,
      size: 9,
      font: helvetica,
      color: COLOR_TEXT_PRIMARY,
    });
    page.drawText(tx.category, {
      x: cols.category.x,
      y: y - 8,
      size: 9,
      font: helvetica,
      color: COLOR_TEXT_SECONDARY,
    });
    page.drawText(sign, {
      x: cols.type.x,
      y: y - 8,
      size: 11,
      font: helveticaBold,
      color: isIncome ? COLOR_INCOME : COLOR_EXPENSE,
    });
    const amount = formatCurrency(tx.amount, tx.currency);
    const aw = helveticaBold.widthOfTextAtSize(amount, 9);
    page.drawText(amount, {
      x: cols.amount.x + cols.amount.width - aw,
      y: y - 8,
      size: 9,
      font: helveticaBold,
      color: isIncome ? COLOR_INCOME : COLOR_EXPENSE,
    });

    y -= 18;
  }

  return y;
}

function drawFooter(ctx: PdfContext, _bottomY: number): void {
  const { page, helvetica, labels, pageNumber } = ctx;
  // Left: "Money Tracker · 2026-07-05 14:32" — page number right-aligned.
  page.drawText(formatDateLocalized(new Date().toISOString(), ctx), {
    x: MARGIN_X,
    y: MARGIN_Y - 18,
    size: 8,
    font: helvetica,
    color: COLOR_TEXT_SECONDARY,
  });
  // Right: "Page N"
  const pageLabel = `${labels.pageLabel} ${pageNumber}`;
  const w = helvetica.widthOfTextAtSize(pageLabel, 8);
  page.drawText(pageLabel, {
    x: PAGE_WIDTH - MARGIN_X - w,
    y: MARGIN_Y - 18,
    size: 8,
    font: helvetica,
    color: COLOR_TEXT_SECONDARY,
  });
  // Top rule
  page.drawLine({
    start: { x: MARGIN_X, y: MARGIN_Y - 10 },
    end: { x: PAGE_WIDTH - MARGIN_X, y: MARGIN_Y - 10 },
    thickness: 0.5,
    color: COLOR_HEADER_RULE,
  });
}

// ─── helpers ────────────────────────────────────────────────────────────────

interface PdfContext {
  pdf: PDFDocument;
  helvetica: PDFFont;
  helveticaBold: PDFFont;
  watermark: Awaited<ReturnType<PDFDocument["embedPng"]>> | null;
  labels: PdfLabel;
  formatCurrency: BuildReportPdfInput["formatCurrency"];
  formatDate: BuildReportPdfInput["formatDate"];
  page: ReturnType<PDFDocument["addPage"]>;
  pageNumber: number;
}

function drawPill(
  page: ReturnType<PDFDocument["addPage"]>,
  helvetica: PDFFont,
  text: string,
  x: number,
  y: number,
  tone: "active" | "archived"
): void {
  const width = helvetica.widthOfTextAtSize(text, 9) + 14;
  const height = 16;
  // pdf-lib has no rounded-rect primitive; for v1 we use a plain rect
  // since the corners are subtle enough not to hurt the look. A future
  // iteration can use the rounded-rect polyline hack if needed.
  const bg = tone === "active" ? rgb(0.86, 0.94, 0.86) : rgb(0.91, 0.91, 0.93);
  const fg = tone === "active" ? COLOR_INCOME : rgb(0.42, 0.45, 0.5);
  page.drawRectangle({
    x,
    y,
    width,
    height,
    color: bg,
  });
  page.drawText(text, {
    x: x + 7,
    y: y + 4,
    size: 9,
    font: helvetica,
    color: fg,
  });
}

function formatDateRange(
  report: BuildReportPdfInput["report"],
  ctx: PdfContext
): string | null {
  const start = report.dateRangeStart
    ? ctx.formatDate(report.dateRangeStart)
    : null;
  const end = report.dateRangeEnd ? ctx.formatDate(report.dateRangeEnd) : null;
  if (!start && !end) return null;
  if (start && end) return `${start} — ${end}`;
  if (start) return `${start} —`;
  return `— ${end}`;
}

// Locale-aware date formatter for "Report · 2026-07-05" and the
// footer. Uses Intl.DateTimeFormat with the user-facing language.
function formatDateLocalized(iso: string, ctx: PdfContext): string {
  const lang = ctx.labels.reportLabel === "Reporte" ? "es" : "en-US";
  const date = new Date(iso);
  return new Intl.DateTimeFormat(lang, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

// Layout helpers reused by the heading + table renderers.
function startNewPageIfNeeded(
  ctx: PdfContext,
  y: number,
  needed: number
): number {
  if (y - needed < MARGIN_Y + 50) {
    ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    ctx.pageNumber += 1;
    drawWatermark(ctx);
    drawHeaderBand(ctx);
    return PAGE_HEIGHT - MARGIN_Y - 50;
  }
  return y;
}

function wrapText(
  helvetica: PDFFont,
  text: string,
  maxWidth: number,
  size: number
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const test = cur.length === 0 ? w : `${cur} ${w}`;
    if (helvetica.widthOfTextAtSize(test, size) > maxWidth && cur.length > 0) {
      lines.push(cur);
      cur = w;
    } else {
      cur = test;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

function truncate(
  helvetica: PDFFont,
  text: string,
  maxWidth: number,
  size: number
): string {
  if (helvetica.widthOfTextAtSize(text, size) <= maxWidth) return text;
  let trimmed = text;
  while (
    trimmed.length > 1 &&
    helvetica.widthOfTextAtSize(`${trimmed}…`, size) > maxWidth
  ) {
    trimmed = trimmed.slice(0, -1);
  }
  return `${trimmed}…`;
}
