#!/usr/bin/env bun
import { exportSchemas } from "@mastra/pg";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..", "..", "..");
const packageJsonPath = resolve(
  projectRoot,
  "packages",
  "mastra-server",
  "node_modules",
  "@mastra",
  "pg",
  "package.json"
);
const { version: pgVersion } = JSON.parse(
  readFileSync(packageJsonPath, "utf8")
) as { version: string };

/**
 * exportSchemas() occasionally emits a DDL statement without the trailing
 * semicolon (see @mastra/pg@1.13.0's `mastra_favorites` index). When that
 * happens, Postgres' parser concatenates the next statement onto it and
 * fails with a syntax error. We split on blank lines (the boundary exportSchemas
 * uses between statements) and append `;` to anything that doesn't end with one.
 */
const ensureSemicolons = (sql: string): string =>
  sql
    .split(/\n\s*\n/)
    .map(stmt => {
      const trimmed = stmt.trimEnd();
      if (!trimmed) return stmt;
      if (/;\s*$/.test(trimmed)) return stmt;
      return trimmed + ";";
    })
    .join("\n\n");

const ddl = exportSchemas("ai");
const lines = ddl.split("\n");
const schemaLines = lines.filter(
  l => !/^\s*CREATE SCHEMA IF NOT EXISTS/i.test(l)
);

const header = [
  "-- ============================================================================",
  `-- Mastra storage schema (@mastra/pg@${pgVersion})`,
  "-- ============================================================================",
  "-- Generated by `bun --filter mastra-server export-schema`. Do not hand-edit.",
  "-- Source: @mastra/pg -> exportSchemas('ai')",
  "--",
  "-- Re-run this script after upgrading @mastra/pg and diff the output against",
  "-- the versioned migration that owns the schema. Tables, indexes, triggers",
  "-- and the per-row timestamp function are owned here so deploys do not",
  "-- depend on Mastra's runtime init running in any particular order. RLS is",
  "-- applied in a sibling migration block; this file is DDL-only.",
  "-- ============================================================================",
  "",
];

const body = [
  ...header,
  ...ensureSemicolons(schemaLines.join("\n")).split("\n"),
  "",
].join("\n");

const defaultDir = resolve(projectRoot, "supabase", "migrations", "_generated");
const defaultFile = resolve(
  defaultDir,
  `mastra_schema_${pgVersion.replace(/\./g, "_")}.sql`
);
const outPath = process.argv[2] ?? defaultFile;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body, "utf8");

process.stderr.write(
  `[mastra] wrote DDL for @mastra/pg@${pgVersion} -> ${outPath}\n`
);
