// export-report-pdf Edge Function
//
// Returns a downloadable PDF of a user-owned report. Used by the
// "Download PDF" button on /reports/:reportId. The build is server-
// side via pdf-lib so the file works identically across clients,
// doesn't ship JS to the browser, and is easier to audit (every byte
// originates on our infrastructure).
//
// Pipeline:
//   1. requireUserAuth — JWT must be valid (mirrors every other function)
//   2. requireCapability('report_pdf_export') — gates the route
//      against users without the capability (free users also get this
//      via payments.default_capabilities; the gate is paid-vs-free's
//      cheaper cousin — same capability table)
//   3. check_and_increment_usage — admin bypass; everyone else counts
//      against the per-period cap in payments.usage_limits
//      (default = 10/month; tester = 500/month). A 429 from the rpc
//      surfaces as the localized "you've reached your monthly limit"
//      toast on the client via getEdgeFunctionErrorMessage.
//   4. fetch report + transactions from public.transactions / public.reports
//   5. fetch perCurrency summary via the get_report_summaries rpc
//   6. load the watermark PNG from _shared/assets at request time
//      (Deno.cwd is the function's dir, so the relative path works)
//   7. buildReportPdf() from _shared/lib/report-pdf → Uint8Array
//   8. respond with application/pdf + Content-Disposition: attachment
//
// Locale: the frontend sends `?lang=es|en` (default `en`); the labels
// object passed to buildReportPdf is one of two hardcoded maps. We
// deliberately don't bring in i18next — a 15-key literal map is
// cheaper than ~50KB of i18n runtime pulled into the Edge function.
//
// URL: GET /functions/v1/export-report-pdf?reportId=<uuid>&lang=es|en
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { requireUserAuth } from "../_shared/auth.ts";
import { CAPABILITIES, requireCapability } from "../_shared/capabilities.ts";
import { getCorsHeaders, handleCorsPreflightRequest } from "../_shared/cors.ts";
import { buildReportPdf, type PdfLabel } from "../_shared/lib/report-pdf.ts";
import { supabase as serviceRoleSupabase } from "../_shared/lib/supabase.ts";

// Per-capability usage counter name — matches the row inserted by the
// migration that grants the capability. Kept here (and not in
// CAPABILITIES) because capability keys are identifiers, not labels.
const USAGE_CAPABILITY = "report_pdf_export";

interface PdfLabels {
  brand: string;
  reportLabel: string;
  statusActive: string;
  statusArchived: string;
  summaryHeader: string;
  income: string;
  expenses: string;
  net: string;
  transactions: string;
  countSuffix: string;
  noTransactions: string;
  tableDate: string;
  tableMerchant: string;
  tableCategory: string;
  tableType: string;
  tableAmount: string;
  pageLabel: string;
  generatedBy: string;
  noDateRange: string;
}

const PDF_LABELS: Record<"en" | "es", PdfLabels> = {
  en: {
    brand: "Money Tracker",
    reportLabel: "Report",
    statusActive: "Active",
    statusArchived: "Archived",
    summaryHeader: "SUMMARY",
    income: "Income",
    expenses: "Expenses",
    net: "Net",
    transactions: "Transactions",
    countSuffix: "transactions",
    noTransactions: "No transactions in this report yet.",
    tableDate: "DATE",
    tableMerchant: "MERCHANT",
    tableCategory: "CATEGORY",
    tableType: "TYPE",
    tableAmount: "AMOUNT",
    pageLabel: "Page",
    generatedBy: "Generated by Money Tracker",
    noDateRange: "No date range",
  },
  es: {
    brand: "Money Tracker",
    reportLabel: "Reporte",
    statusActive: "Activo",
    statusArchived: "Archivado",
    summaryHeader: "RESUMEN",
    income: "Ingresos",
    expenses: "Gastos",
    net: "Neto",
    transactions: "Transacciones",
    countSuffix: "transacciones",
    noTransactions: "Este reporte aún no tiene transacciones.",
    tableDate: "FECHA",
    tableMerchant: "COMERCIO",
    tableCategory: "CATEGORÍA",
    tableType: "TIPO",
    tableAmount: "MONTO",
    pageLabel: "Página",
    generatedBy: "Generado por Money Tracker",
    noDateRange: "Sin rango de fechas",
  },
};

// Locale-aware currency formatter used inside the PDF text. Built on
// top of Intl.NumberFormat so the same backend produces ES-locale
// "1.234,56" vs EN-locale "1,234.56" without depending on the
// frontend's currency.ts utility.
function makeFormatCurrency(locale: "en" | "es") {
  const intlLocale = locale === "es" ? "es-AR" : "en-US";
  const cache = new Map<string, Intl.NumberFormat>();
  return (amount: number, currency: string): string => {
    let fmt = cache.get(currency);
    if (!fmt) {
      fmt = new Intl.NumberFormat(intlLocale, {
        style: "currency",
        currency,
        currencyDisplay: "symbol",
      });
      cache.set(currency, fmt);
    }
    return fmt.format(amount);
  };
}

function makeFormatDate(locale: "en" | "es") {
  const intlLocale = locale === "es" ? "es-AR" : "en-US";
  return (date: string | null): string => {
    if (!date) return "";
    const d = new Date(`${date}T00:00:00Z`);
    return new Intl.DateTimeFormat(intlLocale, {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).format(d);
  };
}

function slugifyFilename(title: string): string {
  const slug = title
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  const stamp = new Date().toISOString().split("T")[0];
  return `report-${slug || "untitled"}-${stamp}.pdf`;
}

Deno.serve(async req => {
  const preflight = handleCorsPreflightRequest(req);
  if (preflight) return preflight;
  const corsHeaders = getCorsHeaders(req);

  if (req.method !== "GET") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    // 1. auth
    const auth = await requireUserAuth(req, corsHeaders);
    if (auth instanceof Response) return auth;
    const { user, role } = auth;
    void user;

    // 2. capability gate
    const cap = await requireCapability(
      { user, role },
      CAPABILITIES.report_pdf_export,
      corsHeaders
    );
    if (cap instanceof Response) return cap;

    // 3. parse + validate reportId
    const url = new URL(req.url);
    const reportId = url.searchParams.get("reportId");
    if (!reportId) {
      return new Response(
        JSON.stringify({ error: "Missing reportId query parameter" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }
    const langParam = url.searchParams.get("lang");
    const locale: "en" | "es" =
      langParam === "es" || req.headers.get("x-user-locale")?.startsWith("es")
        ? "es"
        : "en";

    // 4. usage cap (admin bypass, same pattern as process-document)
    if (role !== "admin") {
      const { data: usage, error: usageError } = await serviceRoleSupabase
        .schema("payments")
        .rpc("check_and_increment_usage", {
          target_user_id: auth.user.id,
          cap: USAGE_CAPABILITY,
        });
      if (usageError) {
        // Fail-open: a counter bug should not block paying users.
        console.error(
          "[export-report-pdf] usage check failed; failing open",
          usageError
        );
      } else if (!(usage as Array<{ allowed: boolean }> | null)?.[0]?.allowed) {
        return new Response(
          JSON.stringify({
            error: `Usage limit exceeded: ${USAGE_CAPABILITY}`,
          }),
          {
            status: 429,
            headers: { ...corsHeaders, "Content-Type": "application/json" },
          }
        );
      }
    }

    // 5. fetch the report — by-id with ownership check via RLS.
    const { data: report, error: reportError } = await serviceRoleSupabase
      .from("reports")
      .select(
        "id, user_id, title, description, status, date_range_start, date_range_end, created_at, archived_at"
      )
      .eq("id", reportId)
      .single();
    if (reportError || !report) {
      return new Response(JSON.stringify({ error: "Report not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    // Defense in depth: RLS already enforces user_id match, but be
    // explicit in case the policy regresses.
    if (report.user_id !== auth.user.id) {
      return new Response(JSON.stringify({ error: "Report not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // 6. fetch transactions in this report (paginate — cap at
    // 1000 rows so a runaway report can't blow up the Edge function).
    const PAGE = 1000;
    const { data: txs, error: txsError } = await serviceRoleSupabase
      .from("transactions")
      .select(
        "id, name, merchant, amount, currency, transaction_type, transaction_date, category"
      )
      .eq("report_id", reportId)
      .eq("discarded", false)
      .order("transaction_date", { ascending: false })
      .range(0, PAGE - 1);
    if (txsError) {
      console.error("[export-report-pdf] transactions fetch failed", txsError);
      return new Response(
        JSON.stringify({ error: "Failed to load transactions" }),
        {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // 7. fetch per-currency summary via the existing RPC. Soft-fail
    // with an empty array if the RPC errors — we'd rather render a
    // PDF with no summary than a 500.
    type RpcSummary = {
      currency: string;
      transaction_count: number;
      total_income: number;
      total_expenses: number;
    };
    const { data: rpcRows } = await serviceRoleSupabase.rpc(
      "get_report_summaries",
      { p_status: report.status }
    );
    const allSummaries = (rpcRows ?? []) as unknown as Array<
      RpcSummary & { id: string }
    >;
    const perCurrency = allSummaries
      .filter(r => r.id === reportId)
      .map(r => ({
        currency: r.currency ?? "",
        transactionCount: Number(r.transaction_count ?? 0),
        totalIncome: Number(r.total_income ?? 0),
        totalExpenses: Number(r.total_expenses ?? 0),
        net: Number(r.total_income ?? 0) - Number(r.total_expenses ?? 0),
      }))
      .filter(b => b.currency !== "");

    // 8. load watermark PNG. the file is co-located in the function
    // dir (export-report-pdf/assets/) so supabase deploy bundles it.
    // _shared/ assets don't resolve correctly in the compiled
    // edge-runtime because import.meta.url points to /var/tmp/...
    let watermarkPng: Uint8Array | null;
    try {
      watermarkPng = await Deno.readFile(
        new URL("./assets/logo-watermark.png", import.meta.url)
      );
    } catch (err) {
      console.error("[export-report-pdf] missing watermark asset:", err);
      watermarkPng = null;
    }

    // 9. build the PDF
    const labels = PDF_LABELS[locale];
    const pdfBytes = await buildReportPdf({
      report: {
        id: report.id,
        title: report.title,
        description: report.description,
        status: report.status,
        dateRangeStart: report.date_range_start,
        dateRangeEnd: report.date_range_end,
        createdAt: report.created_at,
        archivedAt: report.archived_at,
      },
      transactions: (txs ?? []).map(t => ({
        id: t.id,
        name: t.name,
        merchant: t.merchant ?? "",
        amount: Number(t.amount ?? 0),
        currency: t.currency ?? "USD",
        transactionDate: t.transaction_date ?? "",
        category: t.category ?? "",
        transactionType: t.transaction_type ?? "expense",
      })),
      perCurrency,
      watermarkPng,
      labels,
      formatCurrency: makeFormatCurrency(locale),
      formatDate: makeFormatDate(locale),
    });

    // 10. respond with PDF binary. The Content-Disposition makes the
    // browser trigger a download with our filename.
    const filename = slugifyFilename(report.title);
    const headers = {
      ...corsHeaders,
      "Content-Type": "application/pdf",
      "Content-Length": pdfBytes.length.toString(),
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    };

    return new Response(pdfBytes, { status: 200, headers });
  } catch (err) {
    console.error("[export-report-pdf] unhandled error:", err);
    return new Response(
      JSON.stringify({
        error: "Internal server error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
