name: CI

on:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3000
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Instalar Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Instalar dependencias
        run: bun install
      
      - name: Ejecutar lint en backend
        working-directory: packages/backend
        run: bun run lint
      
      - name: Ejecutar lint en frontend
        working-directory: packages/frontend
        run: bun run lint
      
      - name: Ejecutar build en frontend
        working-directory: packages/frontend
        run: bun run build

